name: Build iOS Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build iOS app
        run: |
          xcodebuild \
            -project UE4Dumper-IOS.xcodeproj \
            -scheme UE4Dumper-IOS \
            -configuration Release \
            -sdk iphoneos \
            build \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: UE4Dumper-IOS
          path: |
            /Users/runner/Library/Developer/Xcode/DerivedData/UE4Dumper-IOS-*/Build/Products/Release-iphoneos/UE4Dumper-IOS.app
            
