name: Build iOS Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build iOS app
        run: |
          xcodebuild \
            -project UE4Dumper-IOS/UE4Dumper-IOS.xcodeproj \
            -scheme UE4Dumper-IOS \
            -configuration Release \
            -sdk iphoneos \
            build \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UE4Dumper-IOS-Build
          path: build/Release-iphoneos
